### ISSUE TITLE
use meilisearch-docusearch in docusaurus project

### ISSUE THREAD

**Issue by Lemon5269** [amrbashir/meilisearch-docsearch#97]
I would like to use this plugin in my Docusaurus project. However, when I configure the plugin, the following error occurs:
Error: Docusaurus could not load module at path "/Users/bytedance/code/self_learning/my-website/node_modules/meilisearch-docsearch/dist/index.cjs"
Cause: (0 , import_web.template) is not a function
    at loadFreshModule (/Users/bytedance/code/self_learning/my-website/node_modules/@docusaurus/utils/lib/moduleUtils.js:36:15)
    at normalizePluginConfig (/Users/bytedance/code/self_learning/my-website/node_modules/@docusaurus/core/lib/server/plugins/configs.js:44:65)
    ... 6 lines matching cause stack trace ...
    at async Command.start (/Users/bytedance/code/self_learning/my-website/node_modules/@docusaurus/core/lib/commands/start.js:44:19) {
  [cause]: TypeError: (0 , import_web.template) is not a function
      at /Users/bytedance/code/self_learning/my-website/node_modules/meilisearch-docsearch/dist/index.cjs:51:53
      at evalModule (/Users/bytedance/code/self_learning/my-website/node_modules/jiti/dist/jiti.js:1:256443)
      at jiti (/Users/bytedance/code/self_learning/my-website/node_modules/jiti/dist/jiti.js:1:254371)
      at loadFreshModule (/Users/bytedance/code/self_learning/my-website/node_modules/@docusaurus/utils/lib/moduleUtils.js:33:16)
      at normalizePluginConfig (/Users/bytedance/code/self_learning/my-website/node_modules/@docusaurus/core/lib/server/plugins/configs.js:44:65)
      at /Users/bytedance/code/self_learning/my-website/node_modules/@docusaurus/core/lib/server/plugins/configs.js:98:60
      at Array.map (<anonymous>)
      at loadPluginConfigs (/Users/bytedance/code/self_learning/my-website/node_modules/@docusaurus/core/lib/server/plugins/configs.js:98:38)
      at async initPlugins (/Users/bytedance/code/self_learning/my-website/node_modules/@docusaurus/core/lib/server/plugins/init.js:42:27)
      at async loadPlugins (/Users/bytedance/code/self_learning/my-website/node_modules/@docusaurus/core/lib/server/plugins/index.js:26:21)
      at async load (/Users/bytedance/code/self_learning/my-website/node_modules/@docusaurus/core/lib/server/index.js:76:58)
      at async Command.start (/Users/bytedance/code/self_learning/my-website/node_modules/@docusaurus/core/lib/commands/start.js:44:19)
}
If anyone has encountered this before, could you please tell me how to fix it?

**Comment by FabianLars** [comment]
I can't remember this error and I can't remember what we exactly did to integrate it, but take a look at our tauri-docs repo. It's also a docusaurus repo using this search component, so maybe you can spot the difference 🙏

**Comment by amrbashir** [comment]
Take a look at https://github.com/tauri-apps/meilisearch-docsearch/issues/28 and https://github.com/tauri-apps/tauri-docs/blob/54de0e747978453fe38284d8cb430811c642456a/src/theme/SearchBar/index.js#L9
